spring:
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /static/**
    static-locations: classpath:/static/
server:
  port: 9999
debug: true
app:
  upload:
    image:
      local-path: D:/szxhcl/upload/images/
      url-path: /images/
      allow-types: jpg,jpeg,gif,bmp,png
      max-size: 1000000
      file-name-template: $TIMESTAMP$_$FILENAME$