spring:
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /static/**
    static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 9999
debug: true
app:
  upload:
    image:
      local-path: D:/szxhcl/upload/images/
      url-path: /images/
      allow-types: jpg,jpeg,gif,bmp,png
      max-size: 5000000
      file-name-template: $TIMESTAMP$_$FILENAME$
    file:
      local-path: D:/szxhcl/upload/files/
      url-path: /files/
      max-size: 20000000
      file-name-template: $TIMESTAMP$_$FILENAME$