spring:
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /static/**
    static-locations: classpath:/static/
server:
  port: 9999
debug: true
app:
  upload:
    images:
      local-path: D:/szxhcl/upload/images/
      url-path: /images/